simaiz/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    path('ayuda/', ayuda, name="ayuda"),
    # path('crear_simulacion/', SimFormView.as_view(), name="crear_simulacion"),
    # path('ajax/load-regions/', load_regions, name='ajax_load_regions'),
    # path('crear_app/', AplicacionView.as_view(), name="crear_app"),
    path('direccionar/', direccionar, name='direccionar'),
    path('<username>/crear_simulacion/', crear_simulacion, name='crear_simu'),
    path('<username>/mod_simulacion/<id>/', mod_simulacion, name='mod_simu'),
    path('<username>/', mi_espacio, name='mi_espacio'),
    path('<username>/<op>/', mi_espacio, name='mi_espacio_op'),

]

simaiz/simaiz/main/urls.py
from django.urls import path
from django.config.urls import url
from .views
from .views import inicio

urlpatterns = [
    path('', inicio, name="inicio"),
]

simaiz/simaiz/simaiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.main_urls')),
    path('',include('main.main_urls')),
    path('usuarios/', include('usuarios.url')),
]

simaiz/simaiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('simaiz/', include('main.urls')),
    path('usuarios/', include('usuarios.url')),
    path('configuracion/', include('configuracion.urls')),
]

simaiz/main/models.py
from django.db import models
from django.contrib.auth.models import User
from .choices import *

# Create your models here.

class Planta(models.Model):
    nombre_planta = models.CharField(max_length=50)
    especie = models.CharField(max_length=50)
    dias_ciclo = models.IntegerField()
    agua_req = models.FloatField()

    def __str__(self):
        return self.nombre_planta


class Configuracion(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT)
    precio_maiz = models.FloatField()
    unidadMedidaMaiz = models.CharField(max_length=20)

    def __str__(self):
        return 'Config: %s' %self.usuario


class Fertilizante(models.Model):
    configuracion = models.ForeignKey(Configuracion, null=True, blank=True, on_delete=models.PROTECT)
    nombre_fertilizante = models.CharField(max_length=50)
    porc_nitrogeno = models.FloatField()
    porc_fosforo = models.FloatField()
    porc_potasio = models.FloatField()
    peso = models.FloatField()
    unidadMedidaFert = models.CharField(max_length=20)


    def __str__(self):
        return self.nombre_fertilizante


class Simulacion(models.Model):
    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT)
    nombre_sim = models.CharField(max_length=50)
    semilla = models.CharField(max_length=50)
    fecha_siembra = models.DateField()
    area = models.FloatField()
    unidad_long = models.CharField(max_length=20, choices=UNIDAD_LONG)
    depto = models.CharField(max_length=20, default="")
    zona = models.CharField(max_length=20, default="")
    tipo_suelo = models.CharField(max_length=50, choices=TIPO_SUELO, null=True, blank=True)
    nivel_p = models.CharField(max_length=20, choices=NIVEL, null=True, blank=True)
    nivel_k = models.CharField(max_length=20, choices=NIVEL, null=True, blank=True)
    compartir = models.BooleanField(default=False)


    def __str__(self):
        return self.nombre_sim


class Aplicacion(models.Model):
    simulacion = models.ForeignKey(Simulacion,null=True, blank=True, on_delete=models.CASCADE)
    planta = models.ForeignKey(Planta, null=True, blank=True, on_delete=models.CASCADE)
    fertilizante = models.ForeignKey(Fertilizante, null=True, blank=True, on_delete=models.CASCADE)
    fecha_app = models.DateField()

    def __str__(self):
        return 'aplicacion: %s' %self.planta


class Departamento(models.Model):
    nombre_depto = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre_depto


class Region(models.Model):
    depto = models.ForeignKey(Departamento, null=True, blank=True, on_delete=models.CASCADE)
    estacion = models.CharField(max_length=20)
    zona = models.CharField(max_length=20)

    def __str__(self):
        return 'Region: %s' %self.zona


class Humedad(models.Model):
    region = models.ForeignKey(Region, null=True, blank=True, on_delete=models.CASCADE)
    mes = models.IntegerField()
    promedio = models.FloatField()
    acumulado = models.FloatField()

    def __str__(self):
        return 'humedad: %s' %self.region


class Requerimiento(models.Model):
    clasificacion = models.CharField(max_length=25, null=True, blank=True)
    nitrogeno = models.FloatField()
    fosforo = models.FloatField()
    potasio = models.FloatField()
    
    

simaiz/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render_to_response
from django.views.generic import FormView
from django.urls import reverse_lazy
from random import randint
from django.views.generic import TemplateView
from simaiz.chartjs.views.lines import BaseLineChartView
from .forms_sim import *
from .models import *
from .utilidades import *
from .choices import *
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
import datetime



# Create your views here.

def inicio(request):
    global bloqueo
    bloqueo=False #variable que domina el bloqueo del tiempo
    tiempo_pagina(0)
    hay_busqueda = False
    simulaciones = list()
    haySimu = Simulacion.objects.filter().exists()
    if haySimu:
        sims = Simulacion.objects.filter(compartir=True)
        nomFer = list()
        sList = list()
        for sim in sims:
            applies = Aplicacion.objects.filter(simulacion=sim)
            for ap in applies:
                nomFer.append(ap.fertilizante)
            sList.append(sim)
            sList.append(nomFer)
            simulaciones.append(sList)
            sList = []  # vaciando lista
            nomFer = []  # vaciando los nombre de los fertilizantes

    if request.method == 'POST':
        if 'f_buscar' in request.POST:
            busqueda = request.POST.get('buscar')
            search = busqueda.lower()
            simulaciones = buscar(simulaciones, search)
            if simulaciones:
                hay_busqueda = 'Resultados de la busqueda: ' + busqueda
            else:
                hay_busqueda = 'No se encontro nunguna coincidencia de: ' + busqueda
    if haySimu:
        haySimu = False
    else:
        haySimu = 'No hay ninguna simulacion que haya sido compartidas por los usuarios'
    contexto = {
        'simu': haySimu,
        'busqueda': hay_busqueda,
        'simulaciones': simulaciones,
        'tiempo':tiempo_pagina(1),
    }
    return render(request, "main/index.html", contexto)

def ayuda(request):
    tiempo_pagina(0)
    contexto = {
        'tiempo':tiempo_pagina(1),
    }
    return render(request, 'index.html', contexto)


@login_required()
def direccionar(request):
    if request.user.is_authenticated:
        return redirect('mi_espacio', username=request.user.username)
    else:
        return redirect('inicio')

@login_required()
def mi_espacio(request, username,op='all'):
    agregarDeptosDB() ## metodo para agregar los 14 departamentos
    if username == request.user.username:
        tiempo_pagina(0)
        hay_busqueda=False
        if op=='all' or op=='shared' or op=='private':
            simulaciones=list()
            if op=='all':
                activo=['active','','']
                haySimu=Simulacion.objects.filter(usuario=request.user).exists()
                if haySimu:
                    sims=Simulacion.objects.filter(usuario=request.user)
                    nomFer=list()
                    sList=list()
                    for sim in sims:
                        applies=Aplicacion.objects.filter(simulacion=sim)
                        for ap in applies:
                            nomFer.append(ap.fertilizante)
                        sList.append(sim)
                        sList.append(nomFer)
                        simulaciones.append(sList)
                        sList=[] #vaciando lista
                        nomFer=[] #vaciando los nombre de los fertilizantes
                if request.method=='POST':
                    if 'f_buscar' in request.POST:
                        busqueda=request.POST.get('buscar')
                        search=busqueda.lower()
                        simulaciones=buscar(simulaciones,search)
                        hay_busqueda=True
                    if 'f_delete' in request.POST:
                        id_sim=request.POST.get('id_sim')
                        simulacion=Simulacion.objects.get(id=id_sim)
                        simulacion.delete()
                        return redirect('mi_espacio',username=request.user.username)

            elif op == 'shared':
                activo=['','active','']
                haySimu=Simulacion.objects.filter(compartir=True,usuario=request.user).exists()
                if haySimu:
                    sims=Simulacion.objects.filter(compartir=True,usuario=request.user)
                    nomFer=list()
                    sList=list()
                    for sim in sims:
                        applies=Aplicacion.objects.filter(simulacion=sim)
                        for ap in applies:
                            nomFer.append(ap.fertilizante)
                        sList.append(sim)
                        sList.append(nomFer)
                        simulaciones.append(sList)
                        sList=[] #vaciando lista
                        nomFer=[] #vaciando los nombre de los fertilizantes
                if request.method=='POST':
                    if 'f_buscar' in request.POST:
                        busqueda=request.POST.get('buscar')
                        search=busqueda.lower()
                        simulaciones=buscar(simulaciones,search)
                        hay_busqueda=True
                    if 'f_delete' in request.POST:
                        id_sim=request.POST.get('id_sim')
                        simulacion=Simulacion.objects.get(id=id_sim)
                        simulacion.delete()
                        return redirect('mi_espacio_op',username=request.user.username, op='shared')
            else:
                activo=['','','active']
                haySimu=Simulacion.objects.filter(compartir=False,usuario=request.user).exists()
                if haySimu:
                    sims=Simulacion.objects.filter(compartir=False,usuario=request.user)
                    nomFer=list()
                    sList=list()
                    for sim in sims:
                        applies=Aplicacion.objects.filter(simulacion=sim)
                        for ap in applies:
                            nomFer.append(ap.fertilizante)
                        sList.append(sim)
                        sList.append(nomFer)
                        simulaciones.append(sList)
                        sList=[] #vaciando lista
                        nomFer=[] #vaciando los nombre de los fertilizantes
                if request.method=='POST':
                    if 'f_buscar' in request.POST:
                        busqueda=request.POST.get('buscar')
                        search=busqueda.lower()
                        simulaciones=buscar(simulaciones,search)
                        hay_busqueda=True
                    if 'f_delete' in request.POST:
                        id_sim=request.POST.get('id_sim')
                        simulacion=Simulacion.objects.get(id=id_sim)
                        simulacion.delete()
                        return redirect('mi_espacio_op',username=request.user.username, op='private')

        else:
            return redirect('mi_espacio_op', username=request.user.username, op='all')

        if hay_busqueda:
            if simulaciones:
                hay_busqueda='Resultados de la busqueda: '+busqueda
            else:
                hay_busqueda='No se encontro nunguna coincidencia de: '+busqueda
        if haySimu:
            haySimu=False
        else:
            haySimu='No se encontraron simulaciones'

        contexto = {
            'nombre': request.user.first_name+' '+request.user.last_name,
            'simu':haySimu,
            'simulaciones':simulaciones,
            'busqueda':hay_busqueda,
            'activo':activo,
            'tiempo':tiempo_pagina(1),
        }
        return render(request, "main/mi_espacio.html", contexto)
    else:
        return redirect('mi_espacio', username=request.user.username)

@login_required()
def crear_simulacion(request, username):
    if username == request.user.username:
        tiempo_pagina(0)
        mod=False
        semi=list()
        semillas=list()
        semis=Planta.objects.all()
        for sem in semis:
            semi.append(sem)
            semi.append(sem.dias_ciclo)
            semillas.append(semi)
            semi=[]

        unidades=UNIDAD_LONG
        departamentos=Departamento.objects.all()
        zonas=ZONA
        suelos=TIPO_SUELO
        nutrientes=NIVEL

        try:
            ferPublicos=User.objects.get(id=2)
            configPub=Configuracion.objects.get(usuario=ferPublicos)
        except:
            redirect('mi_espacio',username=request.user.username)
        try:
            configUser=Configuracion.objects.get(usuario=request.user)
        except:
            redirect('configuracion', username=request.user.username)

        ferPub=Fertilizante.objects.filter(configuracion=configPub)
        ferUser=Fertilizante.objects.filter(configuracion=configUser)

        fertilizantes=list()
        for f in ferPub:
            fertilizantes.append(f)
        for f in ferUser:
            fertilizantes.append(f)

        if request.method=='POST': #guardar y direccionar
            if 'f_crear_simu' in request.POST:
                name=request.POST.get('name_simu')
                planta=Planta.objects.get(id=request.POST.get('semilla'))
                fecha_siembra=request.POST.get('fecha_siembra')
                area=request.POST.get('area')
                unidad=request.POST.get('unidad_long')
                depto=request.POST.get('depto')
                zona=request.POST.get('zona')
                analisis=request.POST.get('analisis')
                if analisis=='si_analisis':
                    nivel_p=request.POST.get('fosforo')
                    nivel_k=request.POST.get('potasio')
                    tipo_suelo=''
                else:
                    tipo_suelo=request.POST.get('tipo_suelo')

simaiz/simaiz/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

# Create your views here.

def inicio(request):
	return render(request, "main/index.html", {})


def direccionar(request):
	if request.user:
		return redirect('mi_espacio', username=request.user.username)
	else:
		return redirect('login') 


@login_required()
def mi_espacio(request, username):
	if username==request.user.username:
		contexto = {
		'nombre': request.user.first_name+' '+request.user.last_name,
		}
		return render(request, "main/mi_espacio.html", contexto)
	else:
		return redirect('mi_espacio', username=request.user.username)
	return render(request,"main/index.html",{})

def direccionar(request):
	return redirect('mi_espacio',username=request.user.username)


@login_required()
def mi_espacio(request,username):
	contexto={
		'nombre':request.user.first_name+' '+request.user.last_name,
	}
	return render(request, "main/mi_espacio.html", contexto)

simaiz/templates/main/chart.html
{% extends "base.html" %}

{% block extrahead %}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
$( document ).ready(function() {
    var data = {
        labels: ['1', '5', '10', '15', '20', '25', '30'],
        datasets: [
            {
                label: "Site Registrations in the Last 30 Days",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: {{ 30_day_registrations }}
            }
        ]
    };
    var ctx = document.getElementById("myChart").getContext("2d");
    var myLineChart = new Chart(ctx).Line(data);
});
</script>
{% endblock %}

{% block contenido %}
	<h1 class="text-center">CHARTS SIMAIZ</h1>

<canvas id="myChart" width="500" height="300"></canvas>

{% endblock contenido %}

simaiz/templates/main/index.html
{% extends "base.html" %}
{% load static %}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static "css/main/index.css" %}">
{% endblock css %}
{% block contenido %}
<div class="row">
	<div class="col-12">
		<h1 class="text-center">Simulaciones Compartidas</h1>
	</div>
	<div class="col-12">
		<form method="post" class="form-inline float-right">
			{% csrf_token %}
			<input type="text" name="buscar" class="m-0 buscar" required="" {% if simu %}
                disabled="" 
            {% endif %}>
			<button type="submit" class="btn btn-primary m-0" name='f_buscar' {% if simu %}
                disabled="" 
            {% endif %}><span class="fas fa-search"></span></button>
		</form>
	</div>
</div>

<div class="row">
	<div class="col-12">
		{% if busqueda %}
			<h3 class="text-info">{{busqueda}}</h3>
		{% endif %}
	</div>
</div>
{% if simu %}
    <h2 class="bg-warning text-danger mt-5 p-3">{{simu}}</h2>
{% endif %}
{% for sim in simulaciones %}
    <div class="row simulacion my-3 mx-0">
        <div class="col-12 ">
        	<div class="row titulo">
        		<h3 class="text-center col-12">{{sim.0.nombre_sim}}</h3>
        	</div>
            <div class="row">
                <div class="col-lg-2 col-md-6 col-sm-6"><p class="m-0">USUARIO:</p><p>{{sim.0.usuario.username}}</p></div>
                <div class="col-lg-2 col-md-6 col-sm-6"><p class="m-0">CULTIVO:</p><p>{{sim.0.semilla}}</p></div>
                <div class="col-lg-3 col-md-6 col-sm-6"><p class="m-0">EPOCA DE SIEMBRA:</p><p>{{sim.0.fecha_siembra}}</p></div>
                <div class="col-lg-3 col-md-6 col-sm-6"><p class="m-0">FERTILIZANTES:</p>
                {% for fer in sim.1 %}
                    <p class="m-0">{{fer}}</p>
                {% endfor %}
                </div>
                <div class="col-lg-2 col-md-12 col-sm-12 d-flex flex-column justify-content-center">
                    <div class="row d-flex justify-content-center">
                        <div class="col-lg-12 col-md-6  col-sm-12 my-1">
                            <form method="post" action="{% url 'simulacion' sim.0.id%}">
                                {% csrf_token %}
                                <input class="btn btn-block btn-outline-custom font-weight-bold" type="Submit" name="" value="Visualizar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
	
{% endblock contenido %}

simaiz/templates/main/mi_espacio.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
    Administrar Simulaciones
{% endblock titulo %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/main/mi_espacio.css' %}">
{% endblock css %}
{% block contenido %}
    <p class="alert-info alert font-weight-bold text-center"><span class="">Bienvenido: </span><span class="text-success">{{nombre}}</span></p>
    <h1 class="text-center">Simulacion Maiz y Fertilizantes</h1>
    <br>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <a href="{% url 'crear_simu' request.user%}" class="btn btn-block btn-outline-primary p-3"><span class="font-weight-bold">Crear Simulacion</span></a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <a href="{% url 'configuracion' request.user %}" class="btn btn-block btn-outline-success p-3"><span class="font-weight-bold">Configurar Simulaciones</span></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <form method="post" class="form-inline float-right">
                {% csrf_token %}
                <input type="text" name="buscar" class="m-0 buscar" required="" {% if simu %}
                    disabled="" 
                {% endif %}>
                <button type="submit" class="btn btn-primary m-0" name="f_buscar" {% if simu %}
                    disabled="" 
                {% endif %}><span class="fas fa-search"></span></button>
            </form>
        </div>
    </div>
    <div class="row">
    <div class="col-12">
        {% if busqueda %}
            <h3 class="text-success">{{busqueda}}</h3>
        {% endif %}
    </div>
</div>
    <ul class="nav nav-tabs row mt-3">
        <li class="nav-item col-4 text-center">
            <a href="{% url 'mi_espacio' request.user %}" class="nav-link {{activo.0}}" id="a1">Todas las simulaciones</a>
        </li>
        <li class="nav-item col-4 text-center">
            <a href="{% url 'mi_espacio_op' request.user 'shared'%}" class="nav-link {{activo.1}}" id="a1">Simulaciones Compartidas</a>
        </li>
        <li class="nav-item col-4 text-center">
            <a href="{% url 'mi_espacio_op' request.user 'private'%}" class="nav-link {{activo.2}}" id="a1">Simulaciones Privadas</a>
        </li>
    </ul>
    <div class="container_sim">
    {% if simu %}
        <h2 class="bg-warning text-danger mt-3 text-center p-2">{{simu}}</h2>
    {% endif %}
    {% for sim in simulaciones %}
    <div class="row simulacion my-3 mx-0">
        <div class="col-12">
            <div class="row titulo">
                 <h3 class="text-center col-12 ">{{sim.0.nombre_sim}}</h3>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6"><p>CULTIVO:</p><p>{{sim.0.semilla}}</p></div>
                <div class="col-lg-3 col-md-4 col-sm-6"><p>EPOCA DE SIEMBRA:</p><p>{{sim.0.fecha_siembra}}</p></div>
                <div class="col-lg-3 col-md-4 col-sm-12"><p>FERTILIZANTES:</p>
                {% for fer in sim.1 %}
                    <p class="m-0">{{fer}}</p>
                {% endfor %}
                </div>
                <div class="col-lg-3 col-md-12 col-sm-12">
                    <div class="row my-1">
                        <div class="col-lg-12 col-md-4 my-1">
                            <a href="{% url 'mod_simu' request.user sim.0.id%}" title="" class="btn btn-block btn-primary font-weight-bold">Modificar</a>
                        </div>
                        <div class="col-lg-12 col-md-4 my-1">
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id_sim" value="{{sim.0.id}}">
                                <input class="btn btn-block btn-danger" type="Submit" name="f_delete" value="Eliminar">
                            </form>
                        </div>
                        <div class="col-lg-12 col-md-4 my-1">
                            <form method="post" action="{% url 'simulacion' sim.0.id%}">
                                {% csrf_token %}
                                <input class="btn btn-block btn-success" type="Submit" name="" value="Visualizar">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    <br>
{% endblock contenido %}

simaiz/templates/main/regions_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.pk }}">{{ region.zona }}</option>
{% endfor %}

simaiz/templates/main/simform.html
{% extends 'base.html' %}

{% block contenido %}
<form method="post">
    {% csrf_token %}

    <h3>Crear Simulación: </h3>

    {{ form.as_p }}


    <script>
    $("#id_departamento").change(function () {
      var url = $("#CondicionesForm").attr("data-regions-url");  // get the url of the `load_cities` view
      var DepartamentoId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'depto': DepartamentoId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_region").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

    <input type="submit" value="Guardar" />
</form>

{% endblock %}

simaiz/templates/main/simform2.html
{% extends 'base.html' %}
{% block contenido %}
<h2>CREAR SIMULACION</h2>
<form method="post">

    {% csrf_token %}

    <div class="form-group row">
        <div class="col-sm-3">
            <input name="usuario" id="id_usuario" type="text" value="{{ request.user.username }}" disabled >
        </div>
    </div>

    <div class="form-group row">
        <label for="nombre_sim" class="col-sm-3 col-form-label">Nombre de Simulación</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" name="nombre_sim" id="nombre_sim" placeholder="Nombre">
        </div>
    </div>

    <div class="form-group row">
        <label for="fecha_siembra" class="col-sm-3 col-form-label">Fecha de Siembra</label>
        <div class="col-sm-3">
          <input type="date" class="form-control" name="fecha_siembra" id="fecha_siembra">
        </div>
    </div>

    <div class="form-group row">
        <label for="id_planta" class="col-sm-3 col-form-label">Semilla</label>
        <div class="col-sm-3">
          <select name="semilla" id="id_planta" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for p in plantas %}
                <option value="{{ p.id_planta }}">{{ p.nombre_planta }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="id_unidad_long" class="col-sm-3 col-form-label">Area</label>
        <div class="col-sm-3">
          <input type="number" step="0.01" min="0" class="form-control" name="area" id="area">
        </div>
        <div class="col-sm-3">
          <select name="unidad_long" id="id_unidad_long" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for choice in form.fields.unidad_long.choices %}
                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="id_departamento" class="col-sm-3 col-form-label">Departamento</label>
        <div class="col-sm-3">
          <select name="depto" id="id_departamento" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for d in deptos %}
                <option value="{{ d.id_departamento }}">{{ d.nombre_depto }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="id_region" class="col-sm-3 col-form-label">Zona</label>
        <div class="col-sm-3">
          <select name="planta" id="id_region" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for r in regions %}
                <option value="{{ r.id_region }}">{{ r.zona }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-check">
      <input class="form-check-input" type="radio" name="estudio" id="estudioNo" value="False" checked>
      <label class="form-check-label" for="estudioNo">
        No poseo un Estudio de Suelo
      </label>
      <div class="form-group row">
        <label for="id_tipo_suelo" class="col-sm-3 col-form-label">Tipo de Suelo</label>
        <div class="col-sm-3">
          <select name="tipo_suelo" id="id_tipo_suelo" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for choice in form.fields.tipo_suelo.choices %}
                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                {% endfor %}
            </select>
        </div>
      </div>
    </div>

    <div class="form-check">
      <input class="form-check-input" type="radio" name="estudio" id="estudioSi" value="True">
      <label class="form-check-label" for="estudioSi">
        Poseo un Estudio de Suelo
      </label>
      <div class="form-group row">
        <label for="id_nivel_p" class="col-sm-3 col-form-label">Nivel de Fósforo</label>
        <div class="col-sm-3">
          <select name="nivel_p" id="id_nivel_p" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for choice in form.fields.nivel_p.choices %}
                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                {% endfor %}
            </select>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_nivel_k" class="col-sm-3 col-form-label">Nivel de Potasio</label>
        <div class="col-sm-3">
          <select name="nivel_k" id="id_nivel_k" class="custom-select">
                <option selected>Seleccionar...</option>
                {% for choice in form.fields.nivel_k.choices %}
                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                {% endfor %}
            </select>
        </div>
      </div>
    </div>


    <div class="form-group row">
    <div class="col-sm-3">Compartir</div>
    <div class="col-sm-9">
      <div class="form-check">
        <input name="compartir" class="form-check-input" type="checkbox" id="compartir">
        <label class="form-check-label" for="compartir">
          Compartir esta simulación
        </label>
      </div>
    </div>
  </div>

    <input type="submit" value="Guardar" class="btn btn-success"/>
</form>

{% endblock contenido %}

simaiz/templates/main/simform3.html
{% extends 'base.html' %}
{% block contenido %}
<h2>CREAR SIMULACION</h2>
<form method="post">

    {% csrf_token %}

    {{ aplicacion_form_set.management_form }}
    {% for aplicacion_form in aplicacion_form_set %}

        {{ aplicacion_form.as_p }}

    {% endfor %}
    
    <input type="submit" value="Guardar" class="btn btn-success"/>
</form>

{% endblock contenido %}